# assignment 15 random forest (Company_Data.csv)

In [25]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
pd.options.mode.chained_assignment = None   # its used for some errors are ignoring

In [26]:
data = pd.read_csv('Company_Data.csv')
data.head()


Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [28]:
data['high']=data.Sales.map(lambda x: 1 if x>8 else 0)

# Converting the data type

In [29]:
data['ShelveLoc'] = data['ShelveLoc'].astype ('category')
data['Urban'] = data['Urban'].astype('category')
data['US'] = data['US'].astype('category')

In [30]:
#### data convert category to integer

In [31]:
data['ShelveLoc']=data['ShelveLoc'].cat.codes
data['Urban'] = data['Urban'].cat.codes
data['US'] = data['US'].cat.codes

In [32]:
data.head()

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0   9.50        138      73           11         276    120          0   42   
1  11.22        111      48           16         260     83          1   65   
2  10.06        113      35           10         269     80          2   59   
3   7.40        117     100            4         466     97          2   55   
4   4.15        141      64            3         340    128          0   38   

   Education  Urban  US  high  
0         17      1   1     1  
1         10      1   1     1  
2         12      1   1     1  
3         14      1   1     0  
4         13      1   0     0

In [33]:
data.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc         int8
Age              int64
Education        int64
Urban             int8
US                int8
high             int64
dtype: object

In [34]:
array = data.values

In [35]:
x = array[:,1:11]
y = array[:,11]

In [36]:
print(x)

[[138.  73.  11. ...  17.   1.   1.]
 [111.  48.  16. ...  10.   1.   1.]
 [113.  35.  10. ...  12.   1.   1.]
 ...
 [162.  26.  12. ...  18.   1.   1.]
 [100.  79.   7. ...  12.   1.   1.]
 [134.  37.   0. ...  16.   1.   1.]]


In [37]:
print(y)

[1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0.
 1. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0.
 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0.
 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0.
 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0.

In [38]:
data.describe()

Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000   
mean     7.496325  124.975000   68.657500     6.635000  264.840000   
std      2.824115   15.334512   27.986037     6.650364  147.376436   
min      0.000000   77.000000   21.000000     0.000000   10.000000   
25%      5.390000  115.000000   42.750000     0.000000  139.000000   
50%      7.490000  125.000000   69.000000     5.000000  272.000000   
75%      9.320000  135.000000   91.000000    12.000000  398.500000   
max     16.270000  175.000000  120.000000    29.000000  509.000000   

            Price   ShelveLoc         Age   Education       Urban          US  \
count  400.000000  400.000000  400.000000  400.000000  400.000000  400.000000   
mean   115.795000    1.307500   53.322500   13.900000    0.705000    0.645000   
std     23.676664    0.833475   16.200297    2.620528    0.456614    0.479113   
min     24.000000    0.000000   25.000000   10.000000    0.000000    0.000000   
25%    100.000000    1.000000   39.750000   12.000000    0.000000    0.000000   
50%    117.000000    2.000000   54.500000   14.000000    1.000000    1.000000   
75%    131.000000    2.000000   66.000000   16.000000    1.000000    1.000000   
max    191.000000    2.000000   80.000000   18.000000    1.000000    1.000000   

             high  
count  400.000000  
mean     0.410000  
std      0.492449  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

# Random forest

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [41]:
num_trees = 100
max_feature = 4

In [42]:
kfold = KFold(n_splits = 10 , random_state = 10,shuffle=True)

In [43]:
model = RandomForestClassifier(n_estimators =100, max_features = 5)
model.fit(X_train,Y_train)

RandomForestClassifier(max_features=5)

In [44]:
results = cross_val_score(model , X_train,Y_train, cv =kfold)

In [46]:
print(results.mean())

0.8
